# Use the slim version of the node 14 image as our base
FROM node:20.13.0

# Create a directory for our application in the container 
RUN mkdir -p /usr/src/app

# Set this new directory as our working directory for subsequent instructions
WORKDIR /usr/src/app

# Copy all files in the current directory into the container
COPY . .

# Set the PYTHONPATH environment variable, which is occasionally necessary for certain node packages
# 'PWD' is an environment variable that stores the path of the current working directory
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

# Set up backend URL
ENV VITE_BACK_API_URL=https://buho-dev-423605-back-emvnuo7nva-ew.a.run.app

# Install 'serve', a static file serving package globally in the container
RUN npm install -g serve

# Install all the node modules required by the React app
RUN npm install

# Build the React app
RUN npm run build

# Serve the 'dist' directory on port 8080 using 'serve'
CMD ["serve", "-s", "-l", "8080", "./dist"]